if GetLocale() ~= "ruRU" then return end
if not DBM_GUI_L then DBM_GUI_L = {} end

local L = DBM_GUI_L

--L.MainFrame = "DBM-Amdir"

-- Missing phrases. Start ..
L.Core_GUI					= "Ядро та графічний інтерфейс"
L.Button_MoveBars			= "Перемістити кадри / смуги"
L.Area_BasicSetup			= "Поради щодо початкового настроювання DBM"
L.Area_ModulesForYou		= "Які модулі DBM підходять Вам?"
L.Area_ProfilesSetup		= "Посібник із використання профілів DBM"
L.Panel_ReducedInformation	= "Обсяг інформації"
L.Panel_HandFilter			= "Обсяг роботи з DBM"
L.ResizeOptions				= "Параметри зміни розміру"
L.ResizeInfo				= "Ви можете змінити розмір графічного інтерфейсу, клацнувши в нижньому правому кутку і перетягнути."
L.Button_ResetWindowSize	= "Скинути розмір вікна"
L.Editbox_WindowWidth		= "Ширина вікна"
L.Editbox_WindowHeight		= "Висота вікна"
L.UIGroupingOptions			= "Параметри групування інтерфейсу користувача (зміна цих параметрів вимагає перезавантаження інтерфейсу користувача для будь-якого вже завантаженого мода)"
L.GroupOptionsBySpell		= "Групувати опції мода заклинань (для модів, які це підтримують)"
L.GroupOptionsExcludeIcon	= "Виключити опції 'Set Icon on' (він же 'встановити значок на') з угруповання заклинань (вони будуть згруповані в категорії 'icons', як і раніше)."
L.AutoExpandSpellGroups		= "Автоматичне розширення опцій, згрупованих за заклинаннями"
L.NoDescription				= "Ця здатність не має опису"
L.TabCategory_Alerts		= "Оповіщення"
L.Area_SpecAnnounceConfig	= "Посібник зі спеціальних оголошень візуальних ефектів та звуку"
L.Area_SpecAnnounceNotes	= "Посібник зі спеціальних оголошень"
L.Area_VoicePackInfo		= "Інформація про голосові пакети DBM"
L.Area_BugAlerts			= "Параметри попередження про помилки"
L.BadTimerAlert				= "Показувати повідомлення в чаті, коли DBM виявляє неправильний таймер з помилкою не менше 1 секунди"
L.BadIDAlert				= "Показувати повідомлення в чаті, коли DBM виявляє, що використовується неприпустимий ідентифікатор заклинання або журналу"
L.ShowReminders				= "Показувати нагадування про відсутні сабмоди, відключені сабмоди, виправлення сабмодів, застарілі сабмоди і включений беззвучний режим. Наприклад: DBM-Legion є доповненням до DBM Core."
L.SpecWarn_Vibrate			= "Контролер вібрації"
L.Panel_Appearance			= "Зовнішній вигляд смуг"
L.BarSaturation				= "Насиченість смуг для маленьких таймерів (коли великі смуги відключені): %0.2f"
L.Panel_ColorByType			= "Колір за типом"
L.Panel_Behavior			= "Поведінка смуг"
L.TabCategory_Filters		= "Глобальні відключення та фільтри"
L.Area_DBMFiltersSetup		= "Посібник з фільтрів DBM"
L.Area_SyncMessages			= "Параметри синхронізації аддонів"
L.EnableWBSharing			= "Поділіться, коли Ви кулюєте або перемагаєте світового боса зі своєю гільдією та друзями з Battle.net, які знаходяться в одному ігровому світі."
L.SpamBlockNoSpecWarnFlash			= "Не показувати спеціальне оголошення екранного спалаху"
L.SpamBlockNoSpecWarnVibrate		= "Не вібрувати контролер на спеціальному оголошенні"
L.SpamBlockNoSpecWarnSound			= "Не відтворювати спеціальні звуки оголошень (дозволяють голосові пакети, якщо вони включені на панелі голосових попереджень)"
L.SpamBlockNoTrivialSpecWarnSound	= "Не відтворювати спеціальні звуки оголошень і не показувати спалах екрана для контенту, який є надто простим для Вашого рівня (замість цього відтворює вибраний користувачем звичайний звук оголошення)"
L.Tab_Privacy				= "Контроль конфіденційності"
L.TabCategory_Frames		= "Рамки та інтеграції"
L.Area_NamelateInfo			= "Інформація про аури неймплейтів DBM"
L.Area_General				= "Загальні"
L.Area_Style				= "Стиль"
L.Panel_InfoFrame			= "Інфофрейм"
L.Panel_Range				= "Дистанція"
L.Panel_Nameplates			= "Неймплейти"
L.UseNameplateHandoff		= "Передавати запити аури неймплейтів підтримуваним аддонам (KuiNameplates, Threat Plates, Plater) замість внутрішньої обробки. Це рекомендований варіант, оскільки він дозволяє виконувати більш просунуті функції та налаштування за допомогою надбудови неймплейтів."
L.NPAuraSize				= "Розмір пікселя аури (у квадраті): %d"
L.MissingVoicePack			= "Відсутній голосовий пакет (%s)"
L.RecordOnlyBosses			= "Не записувати треш. Записувати тільки босів.<br/>Використовуйте '/dbm pull' перед босами, щоб до пулу випити зілля і розпочати бій!"
L.DoNotLogLFG				= "Не записувати LFG або LFR (випадкові групи)"
L.LogCurrentMythicRaids		= "Епохальні рейди актуального рівня"
L.LogCurrentRaids			= "Неепохальні рейди актуального рівня (героїчний, нормальний та LFR, якщо фільтр LGF/LFR вимкнено)"
L.LogTWRaids				= "Подорож у часі або рейди часу"
L.LogTrivialRaids			= "Тривіальні рейди (нижче за рівень персонажа)"
L.LogCurrentMPlus			= "Підземелля актуального рівня М+"
L.LogCurrentMythicZero		= "Актуальні підземелля епохального рівня +0"
L.LogTWDungeons				= "Подорож у часі або підземелля часу"
L.LogCurrentHeroic			= "Героїчні підземелля актуального рівня.<br/>Примітка: якщо Ви відвідуєте героїчні підземелля через чергу і хочете, щоб це записувалося, вимкніть фільтр LFG."
L.LogCurrentNormal			= "Звичайні підземелля актуального рівня.<br/>Примітка: якщо Ви відвідуєте звичайні підземелля через чергу і хочете, щоб це записувалося, вимкніть фільтр LFG."
L.LogTrivialDungeons		= "Тривіальні підземелля (нижче за рівень персонажа)"
L.EventEngagePT				= "Встановити звук для запуску таймера пула"
L.Area_ColorBytype			= "Кольорові смуги на кшталт (посібник)"
L.Area_SpamFilter_SpecFeatures		= "Переключити певні функції спеціальних оголошень"
L.Area_SpamFilter_SpecRoleFilters	= "Спеціальні фільтри типів оголошень (контролюють, скільки ручних операцій робить DBM)"
L.SpamSpecRoleDispel				= "Фільтр 'розсіювальних' оповіщень"
L.SpamSpecRoleInterrupt				= "Фільтр сповіщень про переривання"
L.SpamSpecRoleDefensive				= "Фільтр 'захисних' оповіщень"
L.SpamSpecRoleTaunt					= "Фільтр 'провокаційних' оповіщень (для танків 'таунт')"
L.SpamSpecRoleSoak					= "Фільтр 'поглинаючих' оповіщень"
L.SpamSpecRoleStack					= "Фільтр 'high stack' оповіщень"
L.SpamSpecRoleSwitch				= "Фільтр оповіщень про 'зміну мети' & 'аддов'"
L.SpamSpecRoleGTFO					= "Фільтр 'GTFO' оповіщень"
L.Highest							= "Найбільший таймер нагорі"
L.Lowest							= "Найменший таймер нагорі"
-- Missing phrases. End ..

L.TranslationByPrefix		= "Підтримка:"
L.TranslationBy				= "Amdir"
L.Website					= "Сайт: |cFF73C2FBhttps://amdir.in.ua|r | Discord: |cFF73C2FBhttps://discord.gg/jvMBqzsHa6|r"
L.WebsiteButton				= "Сайт"

L.OTabBosses				= "Боси"
L.OTabOptions				= "Налаштування"

L.TabCategory_Options		= "Загальні параметри"
L.TabCategory_OTHER			= "Інші боси"

L.BossModLoaded				= "%s - статистика"
L.BossModLoad_now			= [[Модуль для цих босів не завантажений. Він буде завантажений відразу після входу в підземелля. Також Ви можете натиснути кнопку, щоб завантажити модуль вручну.]]

L.PosX						= "Позиція X"
L.PosY						= "Позиція Y"

L.MoveMe					= "Пересунь мене"
L.Button_OK					= "OK"
L.Button_Cancel				= "Скасування"
L.Button_LoadMod			= "Завантажити модуль"
L.Mod_Enabled				= "Увімкнути модуль"
L.Mod_EnableAnnounce		= "Оголошувати рейду"
L.Mod_Reset					= "Скидання налаштувань"
L.Reset					= "Скидання"

L.Enable					= "Увімк."
L.Disable					= "Вимкнути."

L.NoSound					= "Без звуку"

L.IconsInUse				= "Використовувані мітки"

-- Tab: Boss Statistics
L.BossStatistics			= "Статистика боса"
L.Statistic_Kills			= "Вбивства:"
L.Statistic_Wipes			= "Поразки:"
L.Statistic_Incompletes		= "Не завершено:"
L.Statistic_BestKill		= "Найкращий бій:"
L.Statistic_BestRank		= "Найкращий ранг:"--Maybe not get used, not sure yet, localize anyways

-- Tab: General Core Options
L.General					= "Загальні параметри DBM"
L.EnableMiniMapIcon			= "Відображати кнопку на мінікарті"
L.UseSoundChannel			= "Вибір аудіо каналу для попередження DBM"
L.UseMasterChannel			= "Основний аудіо канал"
L.UseDialogChannel			= "Аудіо канал діалогів"
L.UseSFXChannel				= "Аудіо канал ефектів"
L.Latency_Text				= "Макс. затримка для синхронізації: %d"

L.ModelOptions				= "Налаштування 3D моделей на сторінці босів"
L.EnableModels				= "Показувати 3D моделі босів"
L.ModelSoundOptions			= "Вибір голосового вітання"
L.ModelSoundShort			= "Короткий"
L.ModelSoundLong			= "Довге"

L.Button_RangeFrame			= "Вікно перевірки дистанції"
L.Button_InfoFrame			= "Вікно інформації"
L.Button_TestBars			= "Перевірка індикаторів"
L.Button_ResetInfoRange		= "Скинути інформ./дист. вікна"

-- Tab: Raidwarning
L.Tab_RaidWarning			= "Попередження для рейду"
L.RaidWarning_Header		= "Параметри рейд-попереджень"
L.RaidWarnColors			= "Кольори попереджень для рейду"
L.RaidWarnColor_1			= "Колір 1"
L.RaidWarnColor_2			= "Колір 2"
L.RaidWarnColor_3			= "Колір 3"
L.RaidWarnColor_4			= "Колір 4"
L.InfoRaidWarning			= [[Ви можете вказати розташування та колір попереджень для рейду.
Використовується для повідомлень типу "Гравець X під впливом Y"]]
L.ColorResetted			= "Параметри кольору для цього поля відновлені."
L.ShowWarningsInChat		= "Показувати попередження у вікні чату"
L.ShowFakedRaidWarnings	= "Показувати попередження як \"Оголошення рейду\""
L.WarningIconLeft			= "Відображати значок з лівого боку"
L.WarningIconRight			= "Показувати значок з правого боку"
L.WarningIconChat			= "Відображати значки у вікні чату"
L.WarningAlphabetical		= "Сортувати імена за абеткою"
L.Warn_Duration				= "Тривалість попередження: %0.1f сек"
L.None						= "Ні"
L.Random					= "Випадково"
L.Outline					= "Контур"
L.ThickOutline				= "Товстий контур"
L.MonochromeOutline			= "Монохромний контур"
L.MonochromeThickOutline	= "Монохромний товстий контур"
L.RaidWarnSound				= "Звук рейд-попередження"

-- Tab: Generalwarnings
L.Tab_GeneralMessages		= "Загальні повідомлення"
L.CoreMessages				= "Установки спільних повідомлень"
L.ShowPizzaMessage			= "Показувати повідомлення таймерів, що транслюються, у вікні чату"
L.ShowAllVersions			= "Показувати версії бос мода для всіх членів групи у вікні чату"
L.CombatMessages			= "Параметри повідомлень у бою"
L.ShowEngageMessage			= "Показувати повідомлення про вступ у бій у вікні чату"
L.ShowDefeatMessage			= "Показувати повідомлення про вбивство боса у вікні чату"
L.ShowGuildMessages			= "Показувати повідомлення про вступ у бій/вбивство/вайп рейду гільдії у вікні чату"
L.ShowGuildMessagesPlus		= "Також показувати повідомлення про вступ у бій/вбивство/вайп для групи гільдії в M+ (потрібна опція рейду)"
L.Area_WhisperMessages		= "Параметри приватних повідомлень"
L.AutoRespond				= "Включити автовідповідь у бою"
L.WhisperStats				= "Додавати статистику вбивств/вайпів до автовідповіді"
L.DisableStatusWhisper		= "Вимкнути відповіді на запит статусу бою пошепки для всієї групи (потрібен лідер групи).<br/>Застосовується тільки для звичайних/гер./епох. рейдів та випробувань/епох. підземель"
L.DisableGuildStatus		= "Вимкнути надсилання гільдії повідомлень про прогрес для всієї групи (потрібен лідер групи)"

-- Tab: Barsetup
L.TabCategory_Timers		= "Налаштування індикаторів"
L.BarTexture				= "Текстура індикатора"
L.BarStyle					= "Стиль індикатора"
L.BarDBM					= "DBM"
L.BarSimple					= "Простий (без анімації)"
L.BarStartColor				= "Колір на початку"
L.BarEndColor				= "Колір наприкінці"
L.Bar_Height				= "Висота індикатора: %d"
L.Slider_BarOffSetX		= "Зсув X: %d"
L.Slider_BarOffSetY		= "Зсув Y: %d"
L.Slider_BarWidth			= "Ширина: %d"
L.Slider_BarScale			= "Масштаб: %0.2f"
--Types
L.BarStartColorAdd			= "Початковий колір\n(Помічник)"
L.BarEndColorAdd			= "Кінцевий колір\n(Помічник)"
L.BarStartColorAOE			= "Початковий колір\n(Втрата по області)"
L.BarEndColorAOE			= "Кінцевий колір \n (Втрата по області)"
L.BarStartColorDebuff		= "Початковий колір\n(Мета)"
L.BarEndColorDebuff			= "Кінцевий колір\n(Мета)"
L.BarStartColorInterrupt	= "Початковий колір \n (переривання)"
L.BarEndColorInterrupt		= "Кінцевий колір\n(Переривання)"
L.BarStartColorRole			= "Початковий колір\n(Роль)"
L.BarEndColorRole			= "Кінцевий колір\n(Роль)"
L.BarStartColorPhase		= "Початковий колір \n (Фаза)"
L.BarEndColorPhase			= "Кінцевий колір \n (Фаза)"
L.BarStartColorUI			= "Початковий колір \n (Корист.)"
L.BarEndColorUI				= "Кінцевий колір \n (Корист.)"
--Type 7 options
L.Bar7Header				= "Параметри індикатора користувача"
L.Bar7ForceLarge			= "Завжди використовувати великий індикатор"
L.Bar7CustomInline			= "Використовувати '!' вбудовану іконку"
--Dropdown Options
L.CBTGeneric				= "Загальний"
L.CBTAdd					= "Add"
L.CBTAOE					= "АОЕ"
L.CBTTargeted				= "Ціль"
L.CBTInterrupt				= "Переривання"
L.CBTRole					= "Роль"
L.CBTPhase					= "Фаза"
L.CBTImportant				= "Важливо (Гравець)"
L.CVoiceOne					= "Count Voice 1"
L.CVoiceTwo					= "Count Voice 2"
L.CVoiceThree				= "Count Voice 3"

-- Tab: Timers
L.AreaTitle_BarColors		= "Кольори індикатора типу таймера"
L.AreaTitle_BarSetup		= "Параметри основного індикатора"
L.AreaTitle_Behavior		= "Параметри поведінки смуг"
L.AreaTitle_BarSetupSmall	= "Параметри зменшеного індикатора"
L.AreaTitle_BarSetupHuge	= "Параметри збільшеного індикатора"
L.AreaTitle_BarSetupVariance		= "Параметри зміни смуги"
L.EnableHugeBar			= "Увімкнути збільшений індикатор (Смуга 2)"
L.EnableVarianceBar 				= "Включити зміну смуги"
L.VarianceTransparency				= "Прозорість лінії: %0.1f"
L.VarianceTimerTextBehavior			= "Встановити режим тексту зміни таймера"
L.ZeroatWindowEnds					= "Текст стає рівним нулю наприкінці перезарядки"
L.ZeroatWindowStartPause			= "Текст стає рівним нулю на початку перезарядки, а потім зупиняється"
L.ZeroatWindowStartRestart			= "Текст стає рівним нулю на початку перезаряджання, а потім відновлюється"
L.ZeroatWindowStartNeg				= "Текст стає рівним нулю на початку перезарядки, а потім стає негативним"--По умолчанию
L.BarIconLeft				= "Ліворуч значок"
L.BarIconRight				= "Праворуч"
L.ExpandUpwards				= "Вирівняти по верху"
L.FillUpBars				= "Заливка, що наповнює"
L.ClickThrough				= "Вимкнути події миші (клацання крізь)"
L.Bar_Decimal				= "Відображати десяті, коли час менший: %d"
L.Bar_Alpha					= "Прозорість: %0.1f"
L.Bar_EnlargeTime			= "Збільшувати, коли час менший: %d"
L.BarSpark					= "Іскріння індикатора"
L.BarFlash					= "Миготіння, коли індикатор скоро зникне"
L.BarSort					= "Сортувати за часом"
L.BarColorByType			= "Колір за типом"
L.NoBarFade					= "Використовуйте початкові/кінцеві кольори як маленькі/великі кольори замість поступової зміни кольору"
L.BarInlineIcons			= "Показувати вбудовані іконки"
L.ShortTimerText			= "Використовувати короткий текст таймера (коли доступний)"
L.StripTimerText			= "Обрізати CD / Наступний із таймерів"
L.KeepBar					= "Залишити таймер активним до застосування здатності"
L.KeepBar2					= "(Коли підтримується модулем)"
L.FadeBar					= "Таймери зникнення для здібностей поза діапазоном"

-- Tab: Spec Warn Frame
L.Panel_SpecWarnFrame		= "Спецпопередження для рейду"
L.Area_SpecWarn				= "Налаштування спеціальних попереджень"
L.SpecWarn_ClassColor		= "Використовувати кольори класів для спецпопереджень"
L.ShowSWarningsInChat		= "Показувати спецпопередження у вікні чату"
L.SWarnNameInNote			= "Використовувати SW5 налаштування, якщо замітка користувача містить Ваше ім'я"
L.SpecialWarningIcon		= "Показувати іконки на спеціальних попередженнях"
L.ShortTextSpellname		= "Використовуйте короткий текст назви (якщо є)"
L.SpecWarn_FlashFrameRepeat	= "Повторювати %d раз (якщо включено)"
L.SpecWarn_Flash			= "Екран спалаху"
L.SpecWarn_FlashRepeat		= "Повторювати миготіння"
L.SpecWarn_FlashColor		= "Колір миготіння"
L.SpecWarn_FlashDur			= "Тривалість миготіння: %0.1f"
L.SpecWarn_FlashAlpha		= "Прозорість миготіння: %0.1f"
L.SpecWarn_DemoButton		= "Показати приклад"
L.SpecWarn_ResetMe			= "Відновити промовчання"
L.SpecialWarnSoundOption	= "Встановити звук за замовчуванням"
L.SpecialWarnHeader1		= "Тип 1: встановлення параметрів для звичайних пріоритетних оголошень, що впливають на Вас або Ваші дії"
L.SpecialWarnHeader2		= "Тип 2: встановлення параметрів для об'яв зі звичайним пріоритетом, які впливають на всіх"
L.SpecialWarnHeader3		= "Тип 3: встановлення параметрів для об'яв з ВИСОКИМ пріоритетом"
L.SpecialWarnHeader4		= "Тип 4: встановити параметри для спеціальних оголошень 'Run away' (він же 'утікай') з високим пріоритетом"
L.SpecialWarnHeader5		= "Тип 5: встановлення параметрів для об'яв із примітками, що містять ім'я Вашого гравця"

-- Tab: Spoken Alerts Frame
L.Panel_SpokenAlerts		= "Голосові попередження"
L.Area_VoiceSelection		= "Вибір голосу"
L.CountdownVoice			= "Основний голос для звуків відліку"
L.CountdownVoice2			= "Вторинний голос для звуків відліку"
L.CountdownVoice3			= "Третій голос для звуків відліку"
L.PullVoice					= "Встановити голос для таймерів пулла"
L.VoicePackChoice			= "Голосовий пакет для попереджень"
L.Area_CountdownOptions		= "Налаштування зворотного відліку"
L.Area_VoicePackReplace		= "Варіанти заміни голосового пакета (які озвучують голосові пакети, при включенні відключає звук та замінює)"
L.VPReplaceNote				= "Примітка: голосові пакети не змінюють та не видаляють звуки попередження. Вони просто вимикаються, коли голосовий пакет замінює їх."
L.ReplacesAnnounce			= "Замінити звуки оголошення (примітка: дуже мало хто використовує голосові пакети, за винятком зміни фаз і аддів)"
L.ReplacesSA1				= "Замінити звуки спеціального оголошення 1 (персональний, він же 'pvpflag', які не є GTFO)"
L.ReplacesSA2				= "Замінити звуки спеціального оголошення 2 (все, він же 'beware' -> 'берися')"
L.ReplacesSA3				= "Замінити звуки спеціального оголошення 3 (високопріоритетний звук, він же 'airhorn' -> 'повітряний горн')"
L.ReplacesSA4				= "Замінити звуки спеціального оголошення 4 (високий пріоритет – бігти)"
L.ReplacesGTFO				= "Замінити звуки спеціального оголошення GTFO"
L.ReplacesCustom			= "Замінити спеціальний набір звуків оповіщення (для кожного попередження), (не рекомендується)"
L.Area_VoicePackAdvOptions	= "Додаткові параметри голосового пакета"
L.SWFNever					= "Ніколи"
L.SpecWarn_AlwaysVoice		= "Завжди відтворювати всі голосові попередження (навіть якщо спецпопередження вимкнено).<br/>Корисно для деяких рейд-лідерів у нішевих ситуаціях, інакше не рекомендується."
L.VPDontMuteSounds			= "Вимкнути приглушення звичайних звуків попереджень під час використання голосового пакета (використовуйте це тільки якщо Ви хочете чути ОБИДВА під час попереджень)"
--TODO, maybe add URLS right to GUI panel on where to acquire 3rd party voice packs?
L.Area_VPLearnMore			= "Дізнайтеся більше про голосові пакети та про те, як використовувати ці опції"
L.VPLearnMore				= "|cFF73C2FBhttps://github.com/DeadlyBossMods/DBM-Retail/wiki/%5BGuide%5D-DBM-&-Voicepacks#2022-update|r"
L.Area_BrowseOtherVP		= "Переглянути інші голосові пакети на Curse"
L.BrowseOtherVPs			= "|cFF73C2FBhttps://www.curseforge.com/wow/addons/search?search=dbm+voice|r"
L.Area_BrowseOtherCT		= "Переглянути пакети зворотного відліку на Curse"
L.BrowseOtherCTs			= "|cFF73C2FBhttps://www.curseforge.com/wow/addons/search?search=dbm+count+pack|r"

-- Tab: Event Sounds
L.Panel_EventSounds			= "Звуки подій"
L.Area_SoundSelection		= "Вибір звуку (прокрутіть меню вибору колесом миші)"
L.EventVictorySound			= "Встановити звук під час перемоги у бою"
L.EventWipeSound			= "Встановити звук під час поразки у бою"
L.EventEngageSound			= "Встановити звук під час вступу у бій"
L.EventDungeonMusic			= "Встановити музику в підземеллях/рейдах"
L.EventEngageMusic			= "Встановити музику під час бою"
L.Area_EventSoundsExtras	= "Налаштування звуків подій"
L.EventMusicCombined		= "Дозволити всі варіанти вибору музики для підземель та бою (зміна цієї настройки вимагає перезавантаження інтерфейсу, щоб побачити зміни)"
L.Area_EventSoundsFilters	= "Умови фільтрування звуків подій"
L.EventFilterDungMythicMusic= "Не програвати музику підземелля на епохальній/епохальній складності"
L.EventFilterMythicMusic	= "Не програвати музику бою на епохальній/епохальній складності"

-- Tab: HealthFrame
L.Panel_HPFrame				= "Здоров'я боса"
L.Area_HPFrame				= "Налаштування здоров'я боса"
L.HP_Enabled				= "Завжди відображати здоров'я боса \n (має пріоритет над аналогічним параметром у кожного боса)"
L.HP_GrowUpwards			= "Вирівняти індикатор здоров'я по верху"
L.HP_ShowDemo				= "Індикатор здоров'я"
L.BarWidth					= "Ширина індикатора: %d"

-- Tab: Global Filter
L.Panel_SpamFilter			= "Глобальні відключення та фільтри"
L.Area_SpamFilter_Anounces	= "Глобальне вимкнення та параметри фільтрації"
L.SpamBlockNoShowAnnounce	= "Не показувати текст або відтворювати звук для будь-яких спільних оголошень"
L.SpamBlockNoShowTgtAnnounce= "Не показувати текст або програвати звук для загальних об'яв МЕЦІ (фільтр вище перевизначає цей)"
L.SpamBlockNoSpecWarnText	= "Не показувати текст спецпопереджень, але дозволити голосові пакети (фільтр вище перевизначає цей)"

L.Area_SpamFilter_Timers	= "Функції таймера"
L.SpamBlockNoShowBossTimers			= "Не показувати таймери для босів у підземеллях/рейдах"
L.SpamBlockNoShowTrashTimers		= "Не показувати таймери для трешу в підземеллях/рейдах (Примітка: це також вимикає відновлення здібностей на індикаторах)"
L.SpamBlockNoShowEventTimers		= "Не показувати таймери для подій чи підказок (поява черги, відродження боса тощо)"
L.SpamBlockNoShowUTimers	= "Не показувати таймери, надіслані користувачами (корист./пул/відпочинок)"
L.SpamBlockNoCountdowns		= "Не відтворювати звуки зворотного відліку"

L.Area_SpamFilter_Misc		= "Різне глобальне відключення та параметри фільтра"
L.SpamBlockNoSetIcon		= "Не встановлювати мітки на цілі"
L.SpamBlockNoRangeFrame		= "Не показувати вікно перевірки дистанції"
L.SpamBlockNoInfoFrame		= "Не показувати інформаційне вікно"
L.SpamBlockNoHudMap			= "Не показувати HudMap"
L.Area_SpamFilter_Nameplates= "Глобальне вимкнення Nameplate та параметри фільтрації"
L.SpamBlockNoNameplate		= "Не вказувати Nameplate Auras (вимикає повністю)"
L.SpamBlockNoBossGUIDs		= "Не показувати таймери головного боса (бос 1) на Plater Nameplates як Nameplate Auras\n(Ви все одно будете бачити таймери треша/боса, якщо ця функція включена до Plater)"
L.SpamBlockTimersWithNameplates	= "Не показувати смужки таймера для трешу, якщо в налаштуваннях Plater увімкнено Plater Nameplate Aura CDs (не відноситься до боїв з босами, які завжди показуватимуть смужки таймера)"
L.NameplateFooter			= "Тут доступні додаткові функції, якщо увімкнено функцію Plater Nameplates"
L.SpamBlockNoYells			= "Не надсилати крики в чат"
L.SpamBlockNoNoteSync		= "Не приймати нотатки"

L.Area_Restore				= "Параметри DBM для повернення налаштувань (чи відновлювати попередній корист. стан після закінчення роботи модулів)"
L.SpamBlockNoIconRestore	= "Не зберігати стан міток та відновлювати їх після бою"
L.SpamBlockNoRangeRestore	= "Не відновлювати вікно перевірки дистанції у попередній стан під час приховання модулями"

-- Tab: Spam Filter
L.Area_SpamFilter			= "Параметри спам-фільтра"
L.DontShowFarWarnings		= "Не відображати попередження/таймери для подій, які далеко"
L.StripServerName			= "Видаляти ім'я сервера у попередженнях та таймерах"
L.FilterVoidFormSay			= "Не надсилати в чат позицію/відлік, якщо знаходитесь в $spell:47241"

L.Area_SpecFilter			= "Параметри фільтра по ролі"
L.CurrentSpecRole			= "Роль поточного спека"
L.CurrentSpecRoleDetected	= "Визначено зараз: %s"
L.CurrentSpecRoleTank		= "Танк"
L.CurrentSpecRoleHealer		= "Хіл"
L.CurrentSpecRoleDamager	= "ДД"
L.CurrentSpecRoleUnknown	= "Невідомо"
L.FilterTankSpec			= "Фільтрувати попередження для ролі танка, коли не в спеціалізації танка. (примітка: відключення цього параметра не рекомендується для більшості користувачів, оскільки тепер усі попередження «таунта» включені за замовчуванням)"
L.FilterInterruptsHeader	= "Фільтрувати попередження для спелів, що перериваються, на основі переваг поведінки."
L.FilterInterrupts			= "Якщо кастер не є Вашою поточною метою/фокусом (завжди)"
L.FilterInterrupts2			= "Якщо кастер не є вашою поточною метою/фокусом (завжди) або збити на кд (тільки бос)"
L.FilterInterrupts3			= "Якщо кастер не є Вашою поточною метою/фокусом (завжди) або збити на кд (бос та треш)"
L.FilterInterruptNoteName	= "Фільтрувати попередження для спелів, що перериваються (з лічильником), якщо попередження не містить Ваше ім'я в користь. нотатці"
L.FilterDispels				= "Фільтрувати попередження для розсіюваних спелів, якщо Ваш диспел у кулдауні"
L.FilterTrashWarnings		= "Фільтрувати попередження для трешу у звичайних та героїчних підземеллях"

L.Area_PullTimer			= "Параметри фільтра таймерів пулла/бою/користувань."
L.DontShowPTNoID			= "Блокувати таймер пулла, надісланий з іншої зони"
L.DontShowPT				= "Не відображати індикатор таймера пула"
L.DontShowPTText			= "Не відображати текст оголошення для таймера пулла"
L.DontShowPTCountdownText	= "Не відображати текст відліку таймера пула"
L.DontPlayPTCountdown		= "Не відтворювати звук відліку таймера пулла/бою/користувань."
L.PT_Threshold				= "Не відображати текст відліку таймера пулла/бою/користувань. більше: %d"

L.Area_TimerTracker			= "Параметри TimerTracker"
L.PlayTTCountdown			= "Відтворити звук зворотного відліку TimerTracker"
L.PlayTTCountdownFinished	= "Відтворити звук закінчення зворотного відліку TimerTracker"

L.Panel_HideBlizzard		= "Приховати Blizzard"
L.Area_HideBlizzard			= "Налаштування приховання Blizzard"
L.HideBossEmoteFrame		= "Приховувати вікно емоцій рейдового боса під час бою з босом"
L.SpamBlockRaidWarning		= "Фільтрування попереджень від інших DBM"
L.SpamBlockBossWhispers		= "Фільтрування DBM попереджень пошепки в бою"
L.HideWatchFrame			= "Приховувати вікно відстеження завдань під час бою з босом"
L.HideGarrisonUpdates		= "Приховувати повідомлення із гарнізону під час бою з босом"
L.HideGuildChallengeUpdates	= "Приховувати повідомлення про гільдійські випробування під час бою з босами"
L.HideQuestTooltips			= "Приховувати цілі завдань у підказках під час бою з босами"
L.HideTooltips				= "Приховувати підказки під час бою з босом"
L.DisableSFX				= "Вимкнути канал звукових ефектів під час бою з босами"
L.DisableCinematics			= "Вимкнути внутрішньоігрові ролики"
L.ReportRecount				= "Надсилати звіт Recount після закінчення бою з босом (вимог. помічник)"
L.ReportSkada				= "Надсилати звіт Skada Revisited після закінчення бою з босом (вимог. помічник)"
L.PerCharacterSettings		= "Використовувати окремі профілі для кожного персонажа замість глобального"
L.OnlyFight					= "Тільки під час бою, після того, як ролик був показаний один раз"
L.AfterFirst				= "Після одного перегляду"
L.Always					= "Завжди"
L.CombatOnly				= "Вимкнути в бою (будь-якому)"
L.RaidCombat				= "Вимкнути в бою (тільки боси)"

L.Panel_ExtraFeatures		= "Додаткові можливості"
--
L.Area_ChatAlerts			= "Параметри оповіщень у чаті"
L.RoleSpecAlert				= "Показувати попередження, коли Ваша спеціалізація видобутку не збігається з поточною спеціалізацією при приєднанні до рейду"
L.CheckGear					= "Показувати попередження, коли рівень одягнених предметів набагато нижчий за максимальний (40+)"
L.WorldBossAlert			= "Показувати попередження, коли у Вашому ігровому світі ваші друзі або согільдійці, можливо, вступають у бій з босами поза підземеллям (неточно, якщо відправник у міжсерверній зоні)"
--
L.Area_SoundAlerts			= "Параметри звукових оповіщень"
L.LFDEnhance				= "Програвати звук перевірки готовності для перевірки ролей та запрошень на БГ/ЛФГ через основний аудіо канал"
L.WorldBossNearAlert		= "Програвати звук перевірки готовності, коли неподалік кулять потрібних Вам босів поза підземеллям (перевизначає налаштування для конкретного боса)"
L.RLReadyCheckSound			= "Програвання звуку перевірки готовності під час перевірки готовності через основний аудіо канал або канал діалогів"
L.AFKHealthWarning			= "Звукове сповіщення, якщо Ви втрачаєте здоров'я під час АФК"
L.AutoReplySound			= "Звукове сповіщення при отриманні автовідповіді пошепки від DBM"
--
L.TimerGeneral				= "Параметри таймера"
L.SKT_Enabled				= "Завжди відображати таймер рекордної перемоги (перевизначає налаштування для конкретного боса)"
L.ShowRespawn				= "Відлік до появи боса після вайпа"
L.ShowQueuePop				= "Відлік, що залишився до прийняття черги (пошук групи, БГ і т.д.)"
--
L.Area_AutoLogging			= "Параметри автоматичного запису"
L.Area_AutoLoggingFilters	= "Фільтри автоматичного запису"
L.Area_AutoLoggingContent	= "Вміст автоматичного запису"
L.AutologBosses				= "Автоматично записувати бої з босами, використовуючи журнал бою Blizzard (потрібно використовувати '/dbm pull' перед босами для сумісності з <a href=\"http://www.warcraftlogs.com\">warcraftlogs.com</a>)"
L.AdvancedAutologBosses		= "Автоматично записувати бої з босами, використовуючи Transcriptor"
L.LogOnlyNonTrivial			= "Записувати тільки специфічні бої з рейдовими босами (звичайні або складніші актуальні рейди) та Міф+ підземелля"
--
L.Area_3rdParty				= "Параметри аддонів третіх осіб"
--L.oRA3AnnounceConsumables	= "Announce oRA3 consumables check on combat start"
L.ShowBBOnCombatStart		= "Виконувати перевірку позитивних ефектів Big Brother на початку бою"
L.BigBrotherAnnounceToRaid	= "Оголошувати результати перевірки Big Brother у рейд"
L.Area_Invite				= "Параметри запрошень"
L.AutoAcceptFriendInvite	= "Автоматично приймати запрошення до групи від друзів"
L.AutoAcceptGuildInvite		= "Автоматично приймати запрошення до групи від согільдійців"
L.Area_Advanced				= "Додаткові налаштування"
L.FakeBW					= "Прикидатися BigWigs замість DBM при довірці версій (корисно для гільдій, які змушують використовувати BigWigs)"
L.AITimer					= "Автоматично генеруйте таймери для небачених раніше боїв, використовуючи вбудований AI таймер в DBM (корисно для першого виклику тестового боса, такого як бета-версія або PTR). Примітка: це не буде працювати належним чином для кількох аддів з однією здатністю."
L.FixCLEUOnCombatStart		= "Очищати кеш журналу бою на початку/кінці битви та після зміни зони"

L.Panel_Profile				= "Профілі"
L.Area_CreateProfile		= "Створення профілю налаштувань DBM Core"
L.EnterProfileName			= "Введіть назву профілю"
L.CreateProfile				= "Створити новий профіль зі стандартними налаштуваннями"
L.Area_ApplyProfile			= "Вибір активного профілю"
L.SelectProfileToApply		= "Виберіть профіль для застосування"
L.Area_CopyProfile			= "Копіювання профілю налаштувань DBM Core"
L.SelectProfileToCopy		= "Виберіть профіль для копіювання"
L.Area_DeleteProfile		= "Видалення профілю налаштувань DBM Core"
L.SelectProfileToDelete		= "Виберіть профіль для видалення"
L.Area_DualProfile			= "Налаштування профілю для бос-модулів"
L.DualProfile				= "Увімкнути підтримку різних налаштувань бос-модулів для спеціалізацій.<br/>Керування профілями бос-модулів здійснюється з екрана статистики завантаженого модуля."

L.Area_ModProfile			= "Копіювання налаштувань модуля з іншого персонажа/спека або видалення налаштувань модуля"
L.ModAllReset				= "Скинути всі налаштування модуля"
L.ModAllStatReset			= "Скинути всю статистику модуля"
L.SelectModProfileCopy		= "Копіювати всі налаштування з"
L.SelectModProfileCopySound	= "Копіювати налаштування звуку з"
L.SelectModProfileCopyNote	= "Копіювати нотатки з"
L.SelectModProfileCurrent	= "Поточний профіль для бос-модулів"
L.SelectModProfileDelete	= "Видалити налаштування модуля для"

L.Area_ImportExportProfile	= "Імпорт / експорт профілів"
L.ImportExportInfo			= "Імпорт перезапише Ваш поточний профіль. Робіть це на свій страх та ризик."
L.ButtonImportProfile		= "Імпорт профілю"
L.ButtonExportProfile		= "Експорт профілю"
L.ProfileExportTitle		= "Це ваш поточний профіль із текстовим форматом."
L.ProfileExportSubtitle	= "Натисніть CTRL-С на клавіатурі для копіювання параметрів профілю."
L.ProfileImportTitle		= "Вставити профіль у текстовому форматі."
L.ProfileImportSubtitle	= "Натисніть CTRL-V, щоб вставити текст DBM."

-- Misc
L.FontType					= "Вибір шрифту"
L.FontStyle					= "Прапори шрифту"
L.FontColor					= "Колір шрифту"
L.FontShadow				= "Тінь"
L.FontSize					= "Розмір шрифту: %d"

L.FontHeight	= 16

-- Retail Globals
L.LARGE = "Більше"
L.SMALL = "Менше"
L.PLAYER_DIFFICULTY6 = "Епохальний" -- ID: 24525
L.PLAYER_DIFFICULTY_TIMEWALKER = "Подорож у часі" -- ID: 25846
